# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d05c5b88a5550fc75b938e12e3c19ed8c31848acb981a202b5ab224d7947c07f3c9bff13b78e08304f683a3768725539440188ebb4cf127b7da19fb660d60176

test:
  secret_key_base: 9e5ff9d6cb32f7fbfbf71a7a991261ff4141a5cee0953c263e41c4704ac7b2afbe96295eaab0c13ddc03a34fd7d00e0279d2e5634df3298d4cee8774b7ebb7f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
